carla:
  host: '127.0.0.1'
  port: 2001
  timeout: 5.0
  sync:
    fps: 20
    timeout: 2.0
  seed: 24
  traffic_manager_port: 8001

output_dir: "_out"
max_frames: 3000

weather:
  cloudiness: 0.0
  precipitation: 0.0
  precipitation_deposits: 0.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 30.0
  fog_density: 0.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint:
      name: "vehicle.*"
      attr: {role_name: "hero"}
    transform:
        location: {x: 26.38, y: -57.40, z: 1.5}
    sensors:
    - blueprint:
        name: "sensor.camera.rgb"
        attr: {"image_size_x": "1280", "image_size_y": "960"}
      transform:
        location: {x: 2.0, z: 1.5}
      attachment: "rigid"
    - blueprint:
        name: "sensor.camera.depth"
        attr: {"image_size_x": "1280", "image_size_y": "960"}
      transform:
        location: {x: 2.0, z: 1.5}
      attachment: "rigid"
    - blueprint:
        name: "sensor.camera.instance_segmentation"
        attr: {"image_size_x": "1280", "image_size_y": "960"}
      transform:
        location: {x: 2.0, z: 1.5}
      attachment: "rigid"
