carla:
  host: '127.0.0.1'
  port: 2005
  timeout: 5.0
  sync:
    fps: 20
    timeout: 2.0
  seed: 32
  traffic_manager_port: 8005
  townmap: 'Town03'

output_dir: "_out"
max_frames: 3000

weather:
  cloudiness: 0.0
  precipitation: 0.0
  precipitation_deposits: 0.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 40.0
  fog_density: 0.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint: 
      name: "sensor.camera.instance_segmentation"
      attr: {"image_size_x": "1280", "image_size_y": "960"}
    transform:
      location: {x: 91.76060486, y: -144.2696686, z: 20.0} 
      rotation: {roll: 177.2326965, pitch: 310, yaw: 5.27}
  - blueprint:
      name: "sensor.camera.depth"
      attr: {"image_size_x": "1280", "image_size_y": "960"}
    transform:
      location: {x: 91.76060486, y: -144.2696686, z: 20.0} 
      rotation: {roll: 177.2326965, pitch: 310, yaw: 5.27}
  - blueprint: 
      name: "sensor.camera.rgb"
      attr: {"image_size_x": "1280", "image_size_y": "960"}
    transform: 
      location: {x: 91.76060486, y: -144.2696686, z: 20.0} 
      rotation: {roll: 177.2326965, pitch: 310, yaw: 5.27}
    attachment: "rigid"
